openapi: 3.0.0
info:
  version: 0.0.1
  title: API for Shop Application for Trainees
servers:
  - url: http://localhost:3000
    description: Local Server
  - url: https://dry-hollows-65202.herokuapp.com
    description: Production Server
paths:
  /confirmation:
    post:
      tags:
        - Confirmation
      summary: Confirm email
      requestBody:
        $ref: '#/components/requestBodies/Confirmation'
      responses:
        204:
          $ref: '#/components/responses/NoContent'
        422:
          $ref: '#/components/responses/InvalidConfirmation'
  /categories:
    get:
      tags:
        - Categories
      summary: Get list of Categories
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/CategoryList'
    post:
      tags:
        - Categories
      summary: Create new Category
      security:
        - Token: []
      requestBody:
        $ref: '#/components/requestBodies/Category'
      responses:
        200:
          $ref: '#/components/responses/Category'
        401:
          $ref: '#/components/responses/Unauthorized'
        422:
          $ref: '#/components/responses/InvalidCategory'
  /orders:
    post:
      tags:
        - Orders
      summary: Create new Order
      security:
        - Token: []
      responses:
        201:
          $ref: '#/components/responses/Order'
        401:
          $ref: '#/components/responses/Unauthorized'
  /products/{product_id}/similarities:
    get:
      tags:
        - Products
      summary: Get list of similar Products for a Product
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/ProductList'
  /products:
    get:
      tags:
        - Products
      summary: Get list of Products
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: description
          in: query
          required: false
          schema:
            type: string
        - name: category_id
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          $ref: '#/components/responses/ProductList'
    post:
      tags:
        - Products
      summary: Create new Product
      security:
        - Token: []
      requestBody:
        $ref: '#/components/requestBodies/Product'
      responses:
        200:
          $ref: '#/components/responses/Product'
        401:
          $ref: '#/components/responses/Unauthorized'
        422:
          $ref: '#/components/responses/InvalidProduct'
  /categories/{category_id}/products:
    get:
      tags:
        - Products
      summary: Get list of Products for Category
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: description
          in: query
          required: false
          schema:
            type: string
        - name: category_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          $ref: '#/components/responses/ProductList'
  /purchases:
    post:
      tags:
        - Purchases
      summary: Create new Purchase
      security:
        - Token: []
      requestBody:
        $ref: '#/components/requestBodies/Purchase'
      responses:
        201:
          $ref: '#/components/responses/Purchase'
        401:
          $ref: '#/components/responses/Unauthorized'
        422:
          $ref: '#/components/responses/InvalidPurchase'
  /purchases/{id}:
    patch:
      tags:
        - Purchases
      summary: Edit Purchase
      security:
        - Token: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        $ref: '#/components/requestBodies/Purchase'
      responses:
        200:
          $ref: '#/components/responses/Purchase'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        422:
          $ref: '#/components/responses/InvalidPurchase'
    delete:
      tags:
        - Purchases
      summary: Delete Purchase
      security:
        - Token: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          $ref: '#/components/responses/NoContent'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
  /session:
    post:
      tags:
        - Session
      summary: Sign in
      requestBody:
        $ref: '#/components/requestBodies/Session'
      responses:
        201:
          $ref: '#/components/responses/Session'
        422:
          $ref: '#/components/responses/InvalidSession'
    delete:
      tags:
        - Session
      summary: Sign out
      security:
        - Token: []
      responses:
        204:
          $ref: '#/components/responses/NoContent'
        401:
          $ref: '#/components/responses/Unauthorized'
  /facebook/session:
    post:
      tags:
        - Session
      summary: Sign in via facebook
      requestBody:
        $ref: '#/components/requestBodies/FacebookSession'
      responses:
        201:
          $ref: '#/components/responses/Session'
        422:
          $ref: '#/components/responses/InvalidFacebookSession'
  /version:
    get:
      tags:
        - Version
      summary: Get current app versions
      responses:
        200:
          $ref: '#/components/responses/Version'
  /users:
    post:
      tags:
        - Users
      summary: Sign up
      requestBody:
        $ref: '#/components/requestBodies/User'
      responses:
        201:
          $ref: '#/components/responses/User'
        422:
          $ref: '#/components/responses/InvalidUser'
components:
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        image:
          type: string
          format: uri
    Order:
      type: object
      properties:
        id:
          type: integer
        aasm_state:
          type: string
          enum:
            - created
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        user_id:
          type: integer
        purchases_count:
          type: integer
        total:
          type: number
    Purchase:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        product_id:
          type: integer
        order_id:
          type: integer
          nullable: true
        amount:
          type: integer
        price:
          type: number
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image:
          type: string
          format: url
        description:
          type: string
          nullable: true
        amount:
          type: integer
        price:
          type: number
        discount_price:
          type: number
          nullable: true
        currency:
          type: string
          enum:
            - usd
            - eur
            - uah
        category_ids:
          type: array
          items:
            type: integer
    Version:
      type: object
      properties:
        ios:
          type: object
          properties:
            minimal_recomended:
              type: string
            minimal_compatible:
              type: string
            blocked:
              type: array
              items:
                type: string
        android:
          type: object
          properties:
            minimal_recomended:
              type: string
            minimal_compatible:
              type: string
            blocked:
              type: array
              items:
                type: string
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
          format: email
        roles:
          type: array
          items:
            type: string
            enum:
              - user
              - admin
        currency:
          type: string
  requestBodies:
    Confirmation:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              confirmation:
                type: object
                properties:
                  token:
                    type: string
                    format: uuid
    Purchase:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              purchase:
                type: object
                properties:
                  amount:
                    type: integer
                  product_id:
                    type: integer
    Session:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              session:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                  password:
                    type: string
                    format: password
    FacebookSession:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              session:
                type: object
                properties:
                  access_token:
                    type: string
    User:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              user:
                type: object
                properties:
                  email:
                    type: string
                    format: email
                  password:
                    type: string
                    format: password
                  password_confirmation:
                    type: string
                    format: password
    Category:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              category:
                type: object
                properties:
                  name:
                    type: string
                  image:
                    type: string
                    format: binary
    Product:
      required: true
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              product:
                type: object
                properties:
                  name:
                    type: string
                  image:
                    type: string
                    format: url
                  description:
                    type: string
                    nullable: true
                  amount:
                    type: integer
                  price:
                    type: number
                  discount_price:
                    type: number
                    nullable: true
                  currency:
                    type: string
                    enum:
                      - usd
                      - eur
                      - uah
                  category_ids:
                    type: array
                    items:
                      type: integer
  responses:
    Unauthorized:
      description: Unauthorized
    NotFound:
      description: NotFound
    NoContent:
      description: No Content
    InvalidConfirmation:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: array
                items:
                  type: string
    CategoryList:
      description: Category List
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Category'
    ProductList:
      description: Product List
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Product'
    Order:
      description: Created Order
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Order'
    Purchase:
      description: Created Purchase
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Purchase'
    InvalidPurchase:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
            properties:
              product:
                type: array
                items:
                  type: string
              amount:
                type: array
                items:
                  type: string
    Session:
      description: Created Session
      content:
        application/json:
          schema:
            type: object
            properties:
              auth_token:
                type: string
                format: uuid
              user:
                $ref: '#/components/schemas/User'
    InvalidSession:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: array
                items:
                  type: string
              password:
                type: array
                items:
                  type: string
    InvalidFacebookSession:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
            properties:
              access_token:
                type: array
                items:
                  type: string
    Version:
      description: Version
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Version'
    User:
      description: Created User
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
    InvalidUser:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: array
                items:
                  type: string
              password:
                type: array
                items:
                  type: string
              password_confirmation:
                type: array
                items:
                  type: string
    Category:
      description: Created Category
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Category'
    InvalidCategory:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: array
                items:
                  type: string
              image:
                type: array
                items:
                  type: string
    Product:
      description: Created Product
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
    InvalidProduct:
      description: Validation errors
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: array
                items:
                  type: string
              image:
                type: array
                items:
                  type: string
              description:
                type: array
                items:
                  type: string
              amount:
                type: array
                items:
                  type: string
              price:
                type: array
                items:
                  type: string
              discount_price:
                type: array
                items:
                  type: string
              currency:
                type: array
                items:
                  type: string
              category_ids:
                type: array
                items:
                  type: string
